stages:
  - test

always-run:
  stage: test
  script: echo 'this should always run'

on-pull-requests:
  stage: test
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests

except-pull-requests:
  stage: test
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
